import { z } from "zod";

export const UserPreferenceSchema = z.object({
  id: z.string().optional(), // usually auto-generated by Prisma
  userId: z.string().min(1, "User ID is required"),
  timezone: z.string().default("UTC"),
  dateFormat: z.string().default("DD/MM/YYYY"),
  timeFormat: z.enum(["12h", "24h"]).default("24h"),
  country: z.string().default("IN"),
  currency: z.string().default("INR"),
  measurementSystem: z.enum(["metric", "imperial"]).default("metric"),
  numberFormat: z.string().default("1,23,456.78"),
  weekStart: z.enum(["sunday", "monday"]).default("monday"),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});

export type TUserPreference = z.infer<typeof UserPreferenceSchema>;
